version: "3.9"

services:
  car_showroom:
    build: car_showroom_project/
    command: sh -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./car_showroom_project/:/usr/src/app/
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:14.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=carshowroom
      - POSTGRES_USER=chaddi
      - POSTGRES_PASSWORD=wfii123098
    ports:
      - "5432:5432"

volumes:
  postgres_data:
    driver: local