# Generated by Django 4.0.6 on 2022-07-11 16:36

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('showroom_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('country', django_countries.fields.CountryField(max_length=746, multiple=True)),
                ('found_year', models.IntegerField()),
                ('description', models.TextField()),
                ('number_of_buyers', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'shipper',
            },
        ),
        migrations.CreateModel(
            name='DiscountShipper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.IntegerField(choices=[(0, 'Regular Client'), (3, 'Bronze Client'), (6, 'Silver Client'), (10, 'Gold Client'), (15, 'Platinum Client'), (20, 'Diamond Client')], default=0)),
                ('bought_cars', models.PositiveIntegerField(default=0)),
                ('shipper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipper_discounts', to='shipper_app.shipper')),
                ('showroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='showroom_discounts', to='showroom_app.showroom')),
            ],
            options={
                'db_table': 'shipper_discount',
                'unique_together': {('showroom', 'shipper')},
            },
        ),
    ]
