# Generated by Django 4.0.6 on 2022-08-01 12:22

from django.db import migrations, models
import src.customer.models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='car_characteristics',
            field=models.JSONField(default=src.customer.models.default_characteristics),
        ),
        migrations.AlterField(
            model_name='customer',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=500000.0, max_digits=15),
        ),
    ]
