# Generated by Django 4.0.6 on 2022-07-11 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_app', '0001_initial'),
        ('shipper_app', '0001_initial'),
        ('showroom_app', '0001_initial'),
        ('car_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers_cars', to='customer_app.customer'),
        ),
        migrations.AddField(
            model_name='car',
            name='shipper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shippers_cars', to='shipper_app.shipper'),
        ),
        migrations.AddField(
            model_name='car',
            name='showroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='showrooms_cars', to='showroom_app.showroom'),
        ),
    ]
