# Generated by Django 4.0.6 on 2022-07-11 16:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('country', django_countries.fields.CountryField(max_length=746, multiple=True)),
                ('found_year', models.IntegerField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'showroom',
            },
        ),
        migrations.CreateModel(
            name='DiscountShowroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('amount_of_discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('discount_showroom_for_car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='showroom_car_on_sale', to='car_app.car', verbose_name='car')),
                ('showrooms_discount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='showroom_with_discount', to='showroom_app.showroom', verbose_name='showroom')),
            ],
            options={
                'db_table': 'showroom_discount',
            },
        ),
    ]
