# Generated by Django 4.0.6 on 2022-08-01 11:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('make', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=30)),
                ('body_type', models.CharField(choices=[('SEDAN', 'Седан'), ('COUPE', 'Купе'), ('SPORT', 'Спорткар'), ('WAGON', 'Универсал'), ('HATCHBACK', 'Хэтчбэк'), ('CONVERTIBLE', 'Кабриолет'), ('MINIVAN', 'Минивэн')], max_length=40)),
                ('color', models.CharField(choices=[('RED', 'Красный'), ('GREEN', 'Зеленый'), ('ORANGE', 'Оранжевый'), ('LIGHT_GREY', 'Светло-серый'), ('DARK_GREY', 'Темно-серый'), ('BLACK', 'Черный'), ('WHITE', 'Белый'), ('BLUE', 'Синий')], max_length=40)),
                ('horsepower', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2025)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'db_table': 'car',
            },
        ),
    ]
