# Generated by Django 4.0.6 on 2022-07-22 11:45

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showroom',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
