# Generated by Django 4.0.6 on 2022-08-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showroom',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=500000.0, max_digits=15),
        ),
    ]
